services:
  backend:
    container_name: ${APP_NAME}_backend
    build:
      context: backend
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./backend:/backend
      - ./.env:/.env
      - ./tsconfig.base.json:/tsconfig.base.json
      - ./biome.json:/biome.json
      - ./nodemon.json:/nodemon.json
    ports:
      - ${BACKEND_PORT}:3100
    stdin_open: true
    restart: unless-stopped

  docs:
    container_name: ${APP_NAME}_docs
    build:
      context: docs
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./docs:/docs
      - ./.env:/.env
    ports:
      - ${DOCS_PORT}:3000
    stdin_open: true
    tty: true
    restart: unless-stopped

  postgres:
    container_name: ${APP_NAME}_postgres
    restart: unless-stopped
    image: postgres:${POSTGRES_VERSION}
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
