name: CI
on:
  push:
    branches:
      - main
      - "release/*"
  pull_request:
    branches:
      - "**"

permissions:
  contents: read
  pull-requests: read

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: wagoid/commitlint-github-action@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-backend:
    runs-on: ubuntu-latest
    needs: commitlint
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install packages
        run: npm --prefix backend ci
      - name: build
        run: npm --prefix backend run build

  lint-backend:
    runs-on: ubuntu-latest
    needs: build-backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest
      - name: lint
        run: biome ci .

  test-backend:
    runs-on: ubuntu-latest
    needs: 
      - build-backend
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install packages
        run: npm --prefix backend ci
      - name: test
        run: npm --prefix backend test
